image: python:3.12-alpine

stages:
  - setup
  - runtest

install-dependencies:
  stage: setup
  script:
    - python -m pip install --upgrade pip
	  - pip install -r requirements.txt
  artifacts:
    paths:
      - venv/
    expire_in: 1 hour

testingrun :
  stage: runtest
  script:
    - apk add --no-cache make
    - make run