image: python:3.12-alpine

stages:
  - setup
  - runtest

install-dependencies:
  stage: setup
  script:
    - apk add --no-cache make
    - make environment
    
testingrun :
  stage: runtest
  script:
    - apk add --no-cache make
    - make run